### PR TITLE
Allow adding backorders to stock items

### PR DESCRIPTION
**Pull request by lfolco**
This adds the ability to set the backorders flag in the ProductBuilder

### CODE REVIEW

**Comment by schmengler** [comment]
Thank you for your contributeion, Laura! Unfortunately the tests don't pass yet:

```
PHPUnit 6.5.14 by Sebastian Bergmann and contributors.

.......F............................                              36 / 36 (100%)

Time: 2.22 minutes, Memory: 324.50MB

There was 1 failure:

1) TddWizard\Fixtures\Catalog\ProductBuilderTest::testSimpleProductWithSpecificAttributes
stock backorders
Failed asserting that 0 matches expected 2.

/var/www/magento/vendor/tddwizard/magento2-fixtures/tests/Catalog/ProductBuilderTest.php:115

FAILURES!
Tests: 36, Assertions: 132, Failures: 1.
```

It looks like we need more setup to get extension attributes to work. CI runs tests on 2.3.4 only at the moment though. Does it work for you in later Magento versions?

**Comment by lfolco** [comment]
It's working on 2.3.5, I haven't tried it on earlier versions.

**Comment by schmengler** [comment]
But the tests also fail on 2.3.5 (tried it here: https://app.wercker.com/schmengler/magento2-fixtures/runs/build/5f1eee95dac5630008b63571?step=5f1eeeeeaa6b94000849d59e)

Could you check that?

**Comment by lfolco** [comment]
Tests as passing!

**Comment by schmengler** [comment]
:partying_face:

**Pull request merged**
