### PR TITLE
Adding possibility to create company address

### PR DESCRIPTION
**Pull request by bartoszkubicki**
#45

### CODE REVIEW

**Comment by bartoszkubicki** [comment]
Sure, I will try to write it until next weekend

**Comment by bartoszkubicki** [comment]
@schmengler I had difficulties with running tests because of not existing reference in tests/phpunit.xml.dist:10. I had to test code in some existing magento project. Case seems to be really similar testLocalizedAddresses() so I think it should work. Are test run during these checks here?

**Comment by schmengler** [comment]
@bartoszkubicki yes, it needs to be tested within Magento and tests are run here with Travis CI, but for some reason Travis is not linked in the checks. After the merge conflict is resolved, we'll see if it passes

**Comment by schmengler** [comment]
Solving the conflict via the Github UI had a very weird effect on the build, I'm going to merge your PR as it is looking good to me, and if tests are failing, we'll solve it with a new PR

Thank you!

**Comment by schmengler** [comment]
OK, there are incompatibilities with my latest refactorings, but I'll solve them

**Comment by bartoszkubicki** [comment]
> Solving the conflict via the Github UI had a very weird effect on the build, I'm going to merge your PR as it is looking good to me, and if tests are failing, we'll solve it with a new PR
> 
> Thank you!

Oh yes, in gitlab its the same

**Pull request merged**
