### PR TITLE
add build without save method for products

### PR DESCRIPTION
**Pull request by lfolco**
This adds the ability to create a product without saving it. I tend to use this quite a bit in my own tests and I usually override the ProductBuilder in order to do that.

### CODE REVIEW

**Comment by schmengler** [comment]
Nice addition, thank you!

**Comment by schmengler** [comment]
Unfortunately this breaks on Magento 2.3 because its old PhpUnit version does not support `assertMatchesRegularExpression`. While the 2.3 branch is still supported I would like to stay compatible

**Comment by lfolco** [comment]
Ah! That test was failing in my setup. I'll revert it back.

**Comment by lfolco** [comment]
Changes reverted, although I'm still failing on CodeClimate (not sure what to do about that)

**Comment by schmengler** [comment]
That looks like a false positive, all good :ok_hand:

**Pull request merged**
